In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4,3])

x = np.where(arr == 4) #index of the element 4 in the array
y= np.where(arr == 3)
print(x)
print(y)

(array([3, 5, 6]),)
(array([2, 7]),)


In [6]:
#to filter odd
arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)


In [22]:
#searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
#The searchsorted() method is assumed to be used on sorted arrays.
arr = np.array([6, 7, 9,11,12,15,10,17])

x = np.searchsorted(arr, 10) #should be inserted on index 3 to remain the sort order from left to right
print(x)
arr = np.array([6, 7, 9,11,12,15,9,17])
y=np.searchsorted(arr, 10, side='right') #should be inserted on index 3 to remain the sort order from left to right
print(y)

3
3


In [24]:
#to search multiple value
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


#sorting

In [28]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr,axis=0)) #sort along the first axis
print(np.sort(arr,axis=1)) #sort along the second axis

[[3 0 1]
 [5 2 4]]
[[2 3 4]
 [0 1 5]]


#FILTERING

In [29]:
import numpy as np
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False] #filetering array elements using boolean indexing

newarr = arr[x]

print(newarr)

[41 43]


In [30]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [31]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
