In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2)) #If axis is not explicitly passed, it is taken as 0.

print(arr)

[1 2 3 4 5 6]


In [ ]:
#axis=0 = rows (vertical)
#axis=1 = columns (horizontal)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Split

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:

# We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [14]:
arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6],
                 [ 7,  8,  9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

newarr = np.hsplit(arr, 3) #axis=1 is default for hsplit, so we can also use np.hsplit(arr, 3) instead of np.split(arr, 3, axis=1)

print(newarr)

[array([[[ 1,  2,  3]],

       [[10, 11, 12]]]), array([[[ 4,  5,  6]],

       [[13, 14, 15]]]), array([[[ 7,  8,  9]],

       [[16, 17, 18]]])]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3) #axis=0 is default for vsplit, so we can also use np.vsplit(arr, 3) instead of np.split(arr, 3, axis=0)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6],
                 [ 7,  8,  9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

newarr = np.dsplit(arr, 3) #axis=2 is default for dsplit, so we can also use np.dsplit(arr, 3) instead of np.split(arr, 3, axis=2)

print(newarr)

[array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18]]])]
